release:
  github:
    owner: gleich
    name: Simultaneous-Updates
  prerelease: auto
before:
  hooks:
    - go mod download
builds:
  - goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
brews:
  - tap:
      owner: gleich
      name: homebrew-taps
    folder: Formula
    homepage: 'https://mattglei.ch'
    description: '🏎 One command to update everything'
    commit_author:
      name: gleich
      email: matthewgleich@gmail.com
